# -*- coding: utf-8 -*-
"""funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dYMX_73Jp7VivRl7MVnQiJAPcMDrW52N

**Escreva uma função que receba um número inteiro e imprima o mês
correspondente ao número. Por exemplo, 2 corresponde a “fevereiro”. O
procedimento deve mostrar uma mensagem de erro caso o número recebido não
faça sentido. Gere também um programa que leia um valor e chame a função
criada.**
"""

def calendario(num):
  if(num == 1):
    print("Janeiro")
  if(num == 2):
    print("Fevereiro")
  if(num == 3):
    print("Março")
  if(num == 4):
    print("Abril") 
  if(num == 5):
    print("Maio") 
  if(num == 6):
    print("Junho") 
  if(num == 7):
    print("Julho") 
  if(num == 8):
    print("Agosto") 
  if(num == 9):
    print("Setembro") 
  if(num == 10):
    print("Outubro") 
  if(num == 11):
    print("Novembro") 
  if(num == 12):
    print("Dezembro")     
  if(num > 12 or num < 1 ):
    print("O número não corresponde a um mês :(")

mes = calendario(float(input("Insira um numero inteiro: ")))

"""**Escreva uma função que recebe 2 números inteiros n1 e n2 como entrada e
retorna a soma de todos os números inteiros contidos no intervalo [n1,n2]. Use
esta função em um programa que lê n1 e n2 do usuário e imprime a soma.**
"""

def conta(n1, n2):
  total = 0
  if(n1 > n2):
    n2 = n2 + 1
    while(n1 > n2):
      n1 = n1 - 1
      total = total + n1
  if(n2 > n1):
    n1 = n1 + 1
    while(n2 > n1):
      n2 = n2 - 1
      total = total + n2

  print(total)
n1= float(input("Insira um numero inteiro: "))
n2= float(input("Insira um numero inteiro: "))
result = conta(n1, n2)

"""**Escreva uma função que receba um número natural e imprima os três primeiros
caracteres do dia da semana correspondente ao número. Por exemplo, 7
corresponde a “SAB”. O procedimento deve mostrar uma mensagem de erro caso
o número recebido não corresponda a um dia da semana. Gere também um
programa que utilize essa função, chamando-a, mas antes lendo um valor para
passagem de parâmetro.**
"""

def semana(num):
  if(num == 1):
    print("Dom")
  if(num == 2):
    print("Seg")
  if(num == 3):
    print("Ter")
  if(num == 4):
    print("Qua")
  if(num == 5):
    print("Qui")
  if(num == 6):
    print("Sex")
  if(num == 7):
    print("Sab")
  if(num > 7 or num < 1):
    print("O número não corresponde a um dia da semana.")

dia = semana(float(input("Insira um numero inteiro: ")))

"""**Escreva um programa para ler o número de lados de um polígono regular e a
medida do lado (em cm). Faça uma função que receba como parâmetro o número
de lados e a medida do lado deste polígono e calcule e imprima o seguinte:
• Se o número de lados for igual a 3, escrever TRIÂNGULO e o valor do seu
perímetro.
• Se o número de lados for igual a 4, escrever QUADRADO e o valor da sua área.
• Se o número de lados for igual a 5, escrever PENTÁGONO.**
"""

def conta(lados, medida):
  result = lados * medida
  if(lados == 3):
    print("TRIÂNGULO")
  if(lados == 4):
    print("QUADRADO")
  if(lados == 5):
    print("PENTÁGONO")
    
  return result

lados= float(input("Insira o número de lados: "))
medida= float(input("Insira o numero de medidas: "))
poligono = conta(lados, medida)
print(poligono,"cm")

"""**Escreva um programa para ler as notas das duas avaliações de um aluno no
semestre. Faça uma função que receba as duas notas por parâmetro e calcule e
escreva a média semestral e a mensagem “PARABÉNS! Você foi aprovado!”
somente se o aluno foi aprovado (considere 6.0 a média mínima para aprovação).**
"""

def media (av1, av2):
    media = (av1 + av2) / 2

    if media >= 6:
        print("PARABÉNS! Você foi aprovado.")
    else:
        print("Reprovado")

av1 = float(input("Insira a primeira nota: "))
av2 = float(input("Insira a segunda nota: "))
media(av1, av2)

"""**Faça uma função que calcule a hipotenusa. Os catetos são os dados de entrada e
a hipotenusa é o dado de saída.**
"""

def conta(cat1, cat2):
  result = (cat1 ** 2 + cat2 ** 2) ** (1/2)
  return result

cat1 = float(input("Insira o valor do primeiro cateto: "))
cat2 = float(input("Insira o valor do segundo cateto: "))
hipotenusa = conta(cat1 ,cat2)
print(hipotenusa)

"""**Faça uma função para converter uma temperatura em graus Fahrenheit para
Celsius. A temperatura em Fahrenheit é o dado de entrada e a temperatura em
Celsius é o dado de saída. Utilize a fórmula C = (F - 32) * 5/9, onde F é a
temperatura em Fahrenheit e C é a temperatura em Celsius.**
"""

def converterGrau(fahrenheit):
  conta = (fahrenheit - 32) * 5 / 9
  return conta

celsius = converterGrau(float(input("Digite a temperatura: ")))
print(celsius)

"""**Faça um programa que leia a altura e o sexo (codificado da seguinte forma:
1-feminino 2-masculino) de uma pessoa. Depois faça uma função chamada
pesoideal que receba a altura e o sexo via parâmetro e que calcule e retorne seu
peso ideal, utilizando as seguintes fórmulas:**
"""

def pesoIdeal (altura, sexo):
  
    if sexo == 1:
        fem = (62.1 * altura) - 44.7
        fem = round(fem,2)
        print("Seu peso ideal é de: {}kg".format(fem))
    else:
      if sexo == 2:
        masc = (72.7 * altura) - 58
        masc = round(masc,2)
        print("Seu peso ideal é de: {}kg".format(masc))

sexo = int(input("Digite o sexo, sendo que 1=Feminino / 2=Masc: "))
altura = float(input("Digite sua altura: "))
pesoIdeal(altura, sexo)