# -*- coding: utf-8 -*-
"""Orientação objeto

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1t5pb9VGx0dTVx_Nvt9aIWaHS0ovmgLEj
"""

class Usuario:
  nome = "yasmim"
  sobrenome = "bernardi"
  nomejane = "jane"
  sobrenomejane = "silva"

  def hello(self):
    return "Olá"

usuario1 = Usuario ()
usuario2 = Usuario ()

print (usuario1.hello(), usuario1.nome, usuario1.sobrenome)
print (usuario2.hello(), usuario2.nomejane, usuario2.sobrenomejane)