# -*- coding: utf-8 -*-
"""POO3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MJRQBAD5mnZCWD6Mc4jCq8Y4jyYCIqSF
"""

class Usuario:
    primeiroNome=""

    def hello(self):
        print ("Eu me chamo " + self.primeiroNome)
        return self
    def registrar(self):
        print ("Registro realizado")
        return self
    def mail(self):
        print ("Email enviado")

Usuario1=Usuario()
Usuario1.primeiroNome="Jane"

primeiroNome= Usuario1.hello().registrar().mail()

class Carro:
    modelo=""

    def entrar_carro(self):
        print("O indivíduo entra em seu " + self.modelo)
        return self
    def ligar(self):
        print("O carro está sendo ligado")
        return self
    def dirigir(self):
        print("O carro está sendo dirigido")
        return self
    def frear(self):
        print("O carro está parando")
        return self
    def desligar(self):
        print("O carro está sendo desligado")
        return self

camaro = Carro()
camaro.modelo="Camaro 1970"

modelo= camaro.entrar_carro().ligar().dirigir().frear().desligar()