# -*- coding: utf-8 -*-
"""listaPOO6.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1bWeYaFPKkoUz1w59aCV9dzxZqE2vBhhy
"""

class usuario():
  _nomeUsuario = ""

  def setnome(self, nome):
    self._nome = nome

class admin(usuario):

  def escrevaNome(self):
    return "Admin"
  def digaOla(self):
    return "Olá Admin," + self._nome

admin1 = admin()
admin1.setnome("Baltazar")
print (admin1.digaOla())

"""***Qual é a causa do problema?***
R: A propriedade da classe mãe é privada.
"""

